server {
    listen 80;
    
    # Substitua "_" pelo seu domínio futuramente, caso adicione um,
    # ex: server_name meumercadofacil.com;
    server_name _;

    # Diretório onde o Nginx servirá os arquivos de build
    root /usr/share/nginx/html;
    index index.html;

    # Otimização de cache para arquivos estáticos gerados pelo Vite
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Configuração essencial para React Router funcionar corretamente sem causar erro 404
    location / {
        # Se for um arquivo / URI real, ele serve. Caso contrário, envia para o index.html (React lida com a rota)
        try_files $uri $uri/ /index.html;
    }

    # Tratamento de erro básico
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
